In [17]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Saadet_Nur\programlama_scraping_method\Data\books_bs4.csv")
print("Done!")

Done!

In [18]:
df.head()

                                   title    price rating availability
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

In [19]:
df.columns

Index(['title', 'price', 'rating', 'availability'], dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         100 non-null    object
 1   price         100 non-null    object
 2   rating        100 non-null    object
 3   availability  100 non-null    object
dtypes: object(4)
memory usage: 3.3+ KB

In [21]:
print("Price unique değerleri:")
print(df["price"].unique())

print("\nRating unique değerleri:")
print(df["rating"].unique())

Price unique değerleri:
['Â£51.77' 'Â£53.74' 'Â£50.10' 'Â£47.82' 'Â£54.23' 'Â£22.65' 'Â£33.34'
 'Â£17.93' 'Â£22.60' 'Â£52.15' 'Â£13.99' 'Â£20.66' 'Â£17.46' 'Â£52.29'
 'Â£35.02' 'Â£57.25' 'Â£23.88' 'Â£37.59' 'Â£51.33' 'Â£45.17' 'Â£12.84'
 'Â£37.32' 'Â£30.52' 'Â£25.27' 'Â£34.53' 'Â£54.64' 'Â£22.50' 'Â£53.13'
 'Â£40.30' 'Â£44.18' 'Â£17.66' 'Â£31.05' 'Â£23.82' 'Â£36.89' 'Â£15.94'
 'Â£33.29' 'Â£18.02' 'Â£19.63' 'Â£52.22' 'Â£33.63' 'Â£57.31' 'Â£26.41'
 'Â£47.61' 'Â£23.11' 'Â£45.07' 'Â£31.77' 'Â£50.27' 'Â£14.27' 'Â£18.78'
 'Â£25.52' 'Â£16.28' 'Â£31.12' 'Â£19.49' 'Â£17.27' 'Â£19.09' 'Â£56.13'
 'Â£56.41' 'Â£56.50' 'Â£45.22' 'Â£38.16' 'Â£54.11' 'Â£42.96' 'Â£23.89'
 'Â£16.77' 'Â£20.59' 'Â£37.13' 'Â£56.06' 'Â£58.11' 'Â£49.05' 'Â£40.76'
 'Â£19.73' 'Â£32.24' 'Â£41.83' 'Â£39.58' 'Â£39.25' 'Â£25.02' 'Â£51.04'
 'Â£19.83' 'Â£50.40' 'Â£13.61' 'Â£13.34' 'Â£18.97' 'Â£36.28' 'Â£10.16'
 'Â£15.44' 'Â£48.41' 'Â£46.35' 'Â£14.07' 'Â£14.86' 'Â£33.37' 'Â£56.40'
 'Â£14.02' 'Â£46.91' 'Â£45.61' 'Â£19.92' 'Â£40.11' 'Â£53.90' 'Â£35.67'
 'Â£22.00']

Rating unique değerleri:
['Three' 'One' 'Four' 'Five' 'Two']

In [22]:
df["price"] = (
    df["price"]
    .str.replace("Â£", "", regex=False)
    .astype(float)
)

In [23]:
df.rename(
    columns={
        "price": "price(GBP)"
    },
    inplace=True
)

In [24]:
df.head()

                                   title  price(GBP) rating availability
0                   A Light in the Attic       51.77  Three     In stock
1                     Tipping the Velvet       53.74    One     In stock
2                             Soumission       50.10    One     In stock
3                          Sharp Objects       47.82   Four     In stock
4  Sapiens: A Brief History of Humankind       54.23   Five     In stock

In [25]:
print(df["rating"].unique())

rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

test = df["rating"].replace(rating_map)

print(test.head(10))
print(test.unique())

['Three' 'One' 'Four' 'Five' 'Two']
0    3
1    1
2    1
3    4
4    5
5    1
6    4
7    3
8    4
9    1
Name: rating, dtype: int64
[3 1 4 5 2]

In [27]:
df["rating"] = df["rating"].astype(str).str.strip()

df["rating"] = df["rating"].replace({
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
})

print(df["rating"].unique())

[3 1 4 5 2]

In [28]:
df.head()

                                   title  price(GBP)  rating availability
0                   A Light in the Attic       51.77       3     In stock
1                     Tipping the Velvet       53.74       1     In stock
2                             Soumission       50.10       1     In stock
3                          Sharp Objects       47.82       4     In stock
4  Sapiens: A Brief History of Humankind       54.23       5     In stock

In [30]:
print(df["availability"].unique())

['In stock']

In [31]:
import pandas as pd

output_path = r"C:\Users\Saadet_Nur\programlama_scraping_method\Data\books_cleaned_data.csv"

df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("Dosya kaydedildi:", output_path)

Dosya kaydedildi: C:\Users\Saadet_Nur\programlama_scraping_method\Data\books_cleaned_data.csv